[2021-01-10 01:20:48,787] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-10 01:20:48,788] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:20:49,873] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:20:49,874] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:20:57,155] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [10/Jan/2021 01:20:57] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-10 01:21:53,986] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/Desktop/DATA_PIPELINE (copy)/resources/data_pipeline_resources.py', reloading
[2021-01-10 01:21:54,122] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:21:55,253] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:21:55,254] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:22:49,183] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/Desktop/DATA_PIPELINE (copy)/resources/data_pipeline_resources.py', reloading
[2021-01-10 01:22:49,304] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:22:50,175] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:22:50,176] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:22:59,336] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/Desktop/DATA_PIPELINE (copy)/resources/data_pipeline_resources.py', reloading
[2021-01-10 01:22:59,474] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:23:00,248] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:23:00,249] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:23:08,388] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/Desktop/DATA_PIPELINE (copy)/resources/data_pipeline_resources.py', reloading
[2021-01-10 01:23:08,531] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:23:09,447] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:23:09,447] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:23:20,652] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/Desktop/DATA_PIPELINE (copy)/resources/data_pipeline_resources.py', reloading
[2021-01-10 01:23:20,772] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:23:21,614] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:23:21,615] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:27:41,208] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/Desktop/DATA_PIPELINE (copy)/resources/data_pipeline_resources.py', reloading
[2021-01-10 01:27:41,365] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:27:42,596] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:27:42,597] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:28:03,896] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [10/Jan/2021 01:28:03] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-10 01:28:16,543] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [10/Jan/2021 01:28:16] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-10 01:28:33,228] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [10/Jan/2021 01:28:33] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-10 01:29:48,810] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/Desktop/DATA_PIPELINE (copy)/resources/data_pipeline_resources.py', reloading
[2021-01-10 01:29:49,071] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:29:50,100] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:29:50,101] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:35:23,989] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/Desktop/DATA_PIPELINE (copy)/resources/data_pipeline_resources.py', reloading
[2021-01-10 01:35:24,131] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-10 01:35:24,950] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-10 01:35:24,951] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 339-380-536
[2021-01-10 01:40:44,468] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [10/Jan/2021 01:40:44] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-12 12:47:36,807] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 12:47:38,413] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 12:47:38,423] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 12:47:38,437] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 12:49:31,727] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:49:31] "[33mGET / HTTP/1.1[0m" 404 -
[2021-01-12 12:51:43,091] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:51:43] "[31m[1mGET /data_pipeline/dataset_validation HTTP/1.1[0m" 405 -
[2021-01-12 12:52:02,757] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:52:02] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 12:55:17,648] {_internal.py:113} Thread-5 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:55:17] "[31m[1mPOST /data_pipeline/dataset_validation?dataset_type=SINGULAR&operation=SPELL_CHECKER&input_file=C:\\Users\\Dhanvi\\Spelling_errors\\test_incorrect.csv&encoding=UTF-8&language1=en HTTP/1.1[0m" 400 -
[2021-01-12 12:57:14,944] {_internal.py:113} Thread-6 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:57:14] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 12:57:54,541] {_internal.py:113} Thread-7 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:57:54] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 12:58:43,637] {_internal.py:113} Thread-8 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:58:43] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 12:58:56,080] {_internal.py:113} Thread-9 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:58:56] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 12:59:18,516] {_internal.py:113} Thread-10 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 12:59:18] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:00:53,113] {_internal.py:113} Thread-11 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:00:53] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:04:30,434] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 13:04:30,753] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:04:34,097] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:04:34,110] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:04:34,125] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:04:40,195] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:04:40] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:04:53,124] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 13:04:53,417] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:04:55,679] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:04:55,689] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:04:55,704] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:05:59,234] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\__init__.py', reloading
[2021-01-12 13:05:59,394] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:06:02,672] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:06:02,682] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:06:02,695] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:08:36,360] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:08:36] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:08:59,538] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\__init__.py', reloading
[2021-01-12 13:08:59,746] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:11:26,062] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:11:27,649] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:11:27,658] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:11:27,671] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:11:34,642] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:11:34] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:12:14,773] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 13:12:14,927] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:12:17,467] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:12:17,478] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:12:17,492] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:12:18,123] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:12:18] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:16:41,374] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 13:16:41,707] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:16:43,648] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:16:43,658] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:16:43,671] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:20:27,117] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:20:27] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:21:21,860] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:21:21] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:22:37,855] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 13:22:38,222] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:22:41,215] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:22:41,232] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:22:41,250] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:22:41,737] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:22:41] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:22:49,202] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 13:22:49,465] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:22:52,483] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:22:52,498] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:22:52,516] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:22:52,721] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:22:52] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:23:48,416] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 13:23:48,868] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:23:52,426] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:23:52,446] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:23:52,478] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 13:23:52,966] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 13:23:52] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 13:25:13,720] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\__init__.py', reloading
[2021-01-12 13:25:13,892] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 13:25:16,512] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 13:25:16,531] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 13:25:16,553] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:40:12,507] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:40:14,178] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:40:14,188] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:40:14,200] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:40:19,641] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:40:19] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:40:32,009] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-12 14:40:32,176] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:40:34,302] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:40:34,317] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:40:34,332] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:40:35,177] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:40:35] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:41:40,794] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:41:40] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:42:01,198] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-12 14:42:01,371] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:42:03,657] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:42:03,673] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:42:03,688] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:42:09,709] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:42:09] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:42:38,000] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 14:42:38,188] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:42:40,411] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:42:40,423] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:42:40,440] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:42:43,895] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:42:43] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:43:04,205] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-12 14:43:04,362] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:43:06,356] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:43:06,371] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:43:06,387] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:43:31,205] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 14:43:31,423] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:43:33,611] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:43:33,623] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:43:33,639] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:43:38,200] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:43:38] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:43:51,273] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:43:51] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:44:22,131] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 14:44:22,316] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:44:24,411] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:44:24,432] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:44:24,467] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:44:29,914] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:44:29] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:44:48,175] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 14:44:48,328] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:44:50,366] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:44:50,382] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:44:50,395] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:44:54,896] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:44:54] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-12 14:45:18,902] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 14:45:19,109] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:45:21,008] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:45:21,024] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:45:21,040] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:45:34,195] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 14:45:34,342] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:45:36,294] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:45:36,306] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:45:36,321] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:54:04,940] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 14:54:06,514] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 14:54:06,525] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 14:54:06,538] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 14:54:49,399] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:54:49] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-12 14:58:29,854] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 14:58:29] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-12 15:10:09,565] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-12 15:10:09,768] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 15:10:12,515] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 15:10:12,530] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 15:10:12,547] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 22:25:26,024] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-12 22:25:27,745] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-12 22:25:27,758] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-12 22:25:27,772] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-12 22:25:38,590] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 22:25:38] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-12 22:26:36,818] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Jan/2021 22:26:36] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 11:31:32,433] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 11:31:34,832] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 11:31:34,864] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 11:31:34,888] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 11:31:40,828] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 11:31:40,948] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:31:40] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-13 11:32:18,374] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:32:18] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 11:33:59,453] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:33:59] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 11:34:07,123] {_internal.py:113} Thread-5 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:34:07] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-13 11:41:08,712] {_internal.py:113} Thread-6 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:41:08] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-13 11:41:34,646] {_internal.py:113} Thread-7 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:41:34] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-13 11:45:02,708] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 11:45:03,549] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 11:45:06,738] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 11:45:06,754] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 11:45:06,782] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 11:45:11,349] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:45:11] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-13 11:45:55,673] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 11:45:56,066] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 11:45:59,836] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 11:45:59,851] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 11:45:59,875] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 11:46:04,799] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:46:04] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 11:47:37,123] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:47:37] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 11:47:53,328] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 11:47:53,593] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 11:47:57,420] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 11:47:57,436] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 11:47:57,457] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 11:49:17,720] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:49:17] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-13 11:49:34,218] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 11:49:34,514] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 11:49:37,917] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 11:49:37,933] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 11:49:37,949] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 11:49:42,513] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 11:49:42] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:40:01,547] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:40:01] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:40:33,704] {utils.py:141} Thread-4 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 13:40:33,754] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:40:33] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:41:05,379] {_internal.py:113} Thread-5 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:41:05] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:41:12,776] {_internal.py:113} Thread-6 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:41:12] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:45:18,226] {_internal.py:113} Thread-7 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:45:18] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:45:31,800] {_internal.py:113} Thread-8 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:45:31] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 13:45:42,894] {_internal.py:113} Thread-9 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:45:42] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:49:54,608] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 13:49:55,418] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 13:50:02,476] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 13:50:02,499] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 13:50:02,523] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 13:51:46,930] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:51:46] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:52:26,504] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:52:26] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 13:52:38,330] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:52:38] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 13:54:02,017] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 13:54:02,213] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 13:54:04,962] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 13:54:04,979] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 13:54:04,997] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 13:54:13,649] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 13:54:13,914] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 13:54:19,488] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 13:54:19,509] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 13:54:19,529] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 13:56:02,988] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 13:56:03,047] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:56:03] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 13:59:14,607] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 13:59:14] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 14:06:13,492] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:06:13,896] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:06:18,161] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:06:18,179] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:06:18,207] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:07:39,487] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 14:07:39,759] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:07:43,129] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:07:43,153] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:07:43,207] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:24:11,820] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:24:11] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:38:15,360] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:38:15,600] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:38:17,791] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:38:17,801] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:38:17,815] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:38:23,371] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:38:23] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:39:03,442] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 14:39:03,611] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:39:05,683] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:39:05,694] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:39:05,708] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:39:11,150] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:39:11] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:40:08,246] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:40:08,530] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:40:10,843] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:40:10,856] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:40:10,872] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:40:11,759] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:40:11] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:41:38,569] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:41:38,740] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:41:57,286] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:41:59,303] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:41:59,314] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:41:59,328] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:42:03,585] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:42:03] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:42:53,012] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:42:53,199] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:42:55,330] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:42:55,342] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:42:55,356] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:43:05,346] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:43:05] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:43:39,944] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:43:40,257] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:43:42,321] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:43:42,334] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:43:42,348] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:43:49,275] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:43:49] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:44:06,234] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:44:06,401] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:44:08,869] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:44:08,887] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:44:08,906] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:44:20,110] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:44:20] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:45:27,006] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:45:27,337] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:45:29,388] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:45:29,400] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:45:29,417] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:45:32,730] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:45:32] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:45:55,973] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:45:56,145] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:45:58,520] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:45:58,535] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:45:58,548] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:47:39,355] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:47:39,532] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:47:42,541] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:47:42,552] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:47:42,565] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:47:46,617] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:47:46] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 14:49:40,953] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:49:41,129] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:49:43,741] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:49:43,756] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:49:43,773] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:49:47,140] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:49:47] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 14:50:23,433] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:50:23,618] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:50:26,184] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:50:26,199] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:50:26,215] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:50:29,249] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:50:29] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 14:50:57,738] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:50:57,909] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:51:00,337] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:51:00,353] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:51:00,368] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:51:07,297] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:51:07] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 14:56:46,530] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:56:46,688] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:57:26,883] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:57:28,825] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:57:28,836] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:57:28,850] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:57:33,150] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:57:33] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:57:47,118] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:57:47,512] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:57:50,381] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:57:50,393] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:57:50,406] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:57:53,627] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:57:53] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:58:54,581] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:58:54,834] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:58:57,271] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:58:57,283] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:58:57,298] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:59:01,045] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:59:01] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 14:59:28,982] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:59:29,190] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 14:59:31,813] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 14:59:31,828] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 14:59:31,846] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 14:59:48,118] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 14:59:48] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 14:59:57,243] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 14:59:57,480] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:00:01,023] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:00:01,048] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:00:01,099] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:00:02,324] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:00:02] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 15:04:57,630] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:04:59,381] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:04:59,391] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:04:59,404] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:05:07,801] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 15:05:07,900] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:05:07] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-13 15:05:31,662] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:05:31] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-13 15:32:02,339] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 15:32:02,795] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:32:05,431] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:32:05,447] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:32:05,473] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:32:22,903] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:32:22] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 15:33:12,457] {utils.py:141} Thread-3 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 15:33:12,564] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:33:12] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 15:33:59,220] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 15:33:59,677] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:34:02,164] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:34:02,175] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:34:02,190] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:34:09,399] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 15:34:10,083] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:34:10] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 15:35:12,283] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 15:35:12,620] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:35:14,951] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:35:14,963] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:35:14,976] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:35:21,421] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 15:35:21,784] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:35:21] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 15:36:13,385] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:36:13] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 15:37:42,044] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 15:37:42,536] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:37:44,867] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:37:44,880] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:37:44,893] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:37:46,666] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 15:37:47,215] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:37:47] "[35m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 500 -
[2021-01-13 15:37:59,072] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 15:37:59,511] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:38:02,411] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:38:02,433] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:38:02,452] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:38:03,344] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 15:38:04,225] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:38:04] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 15:38:40,662] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 15:38:40,983] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:38:43,229] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:38:43,241] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:38:43,255] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:39:17,298] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 15:39:17,586] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:39:17] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 15:39:40,198] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:39:40] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-13 15:40:13,773] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-13 15:40:14,090] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:40:16,933] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:40:16,949] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:40:16,968] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:40:23,004] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-13 15:40:23,299] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-13 15:40:26,117] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-13 15:40:26,128] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-13 15:40:26,145] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-13 15:40:32,126] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-13 15:40:32,974] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [13/Jan/2021 15:40:32] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:08:10,384] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 11:08:12,552] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 11:08:12,567] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 11:08:12,587] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 11:09:00,479] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-18 11:09:01,784] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:09:01] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:10:40,054] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:10:40] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:15:05,713] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:15:05] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:21:51,085] {_internal.py:113} Thread-5 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:21:51] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:38:30,302] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 11:38:32,216] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 11:38:32,229] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 11:38:32,248] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 11:38:58,784] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-18 11:38:59,446] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:38:59] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:39:20,157] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-18 11:39:20,606] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 11:39:22,812] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 11:39:22,822] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 11:39:22,835] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 11:39:24,356] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-18 11:39:24,616] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 11:39:26,746] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 11:39:26,760] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 11:39:26,776] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 11:39:31,724] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-18 11:39:32,392] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:39:32] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:41:43,003] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-18 11:41:43,677] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 11:41:45,986] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 11:41:46,010] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 11:41:46,153] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 11:41:51,530] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-18 11:41:52,339] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:41:52] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:42:19,114] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-18 11:42:19,732] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 11:42:22,221] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 11:42:22,231] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 11:42:22,245] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 11:42:33,047] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-18 11:42:33,238] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 11:42:35,677] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 11:42:35,688] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 11:42:35,701] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 11:42:41,039] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-18 11:42:41,699] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:42:41] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 11:42:56,419] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\resources\\data_pipeline_resources.py', reloading
[2021-01-18 11:42:56,960] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 11:42:58,992] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 11:42:59,004] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 11:42:59,018] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 11:43:04,613] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-18 11:43:05,259] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:43:05] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 11:43:33,485] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 11:43:33] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 13:03:04,658] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 13:03:06,353] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 13:03:06,365] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 13:03:06,380] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 13:03:31,929] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-18 13:03:32,578] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 13:03:32] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 14:04:33,878] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:04:35,504] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:04:35,515] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 14:04:35,532] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 14:04:51,535] {utils.py:141} Thread-2 INFO in utils: NumExpr defaulting to 4 threads.
[2021-01-18 14:04:51,819] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:04:51] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 14:05:13,929] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:05:13] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 14:12:12,442] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:12:12] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 14:28:35,082] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:28:36,974] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:28:36,986] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 14:28:37,001] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 14:28:48,146] {_internal.py:113} MainThread INFO in _internal:  * Detected change in 'C:\\Users\\Dhanvi\\Wikipedia_Crawler\\data-validation-pipeline\\utilities\\spell_checker\\spell_corrector.py', reloading
[2021-01-18 14:28:48,461] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:28:50,987] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:28:50,997] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 959-620-893
[2021-01-18 14:28:51,011] {_internal.py:113} Thread-1 INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 14:29:07,177] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:29:07] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 14:28:30,131] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 14:28:30,134] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:28:31,685] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:28:31,686] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 14:28:36,140] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:28:36] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 14:33:05,928] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:33:05] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 14:33:31,460] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/JAN_18_PIPELINE/anuvaad-corpus-tools/data-validation-pipeline/utilities/spell_checker/spell_corrector.py', reloading
[2021-01-18 14:33:31,704] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:33:34,488] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:33:34,495] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 14:33:36,586] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/JAN_18_PIPELINE/anuvaad-corpus-tools/data-validation-pipeline/utilities/spell_checker/spell_corrector.py', reloading
[2021-01-18 14:33:37,003] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:33:38,631] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:33:38,631] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 14:33:40,587] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:33:40] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 14:34:33,836] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/JAN_18_PIPELINE/anuvaad-corpus-tools/data-validation-pipeline/utilities/spell_checker/spell_corrector.py', reloading
[2021-01-18 14:34:34,257] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:34:35,959] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:34:35,960] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 14:34:38,311] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:34:38] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 14:36:02,079] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 14:36:02,080] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:36:03,103] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:36:03,103] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 14:36:08,813] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:36:08] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 14:36:31,723] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/JAN_18_PIPELINE/anuvaad-corpus-tools/data-validation-pipeline/utilities/spell_checker/spell_corrector.py', reloading
[2021-01-18 14:36:32,028] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:36:34,189] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:36:34,193] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 14:36:37,962] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:36:37] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 14:39:10,600] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 14:39:10,602] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:39:12,084] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:39:12,092] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 14:39:16,219] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/JAN_18_PIPELINE/anuvaad-corpus-tools/data-validation-pipeline/utilities/spell_checker/spell_corrector.py', reloading
[2021-01-18 14:39:16,415] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 14:39:17,896] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 14:39:17,897] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 14:39:25,673] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 14:39:25] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 23:43:36,114] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-18 23:43:36,115] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 23:43:37,102] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 23:43:37,103] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 23:43:53,943] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 23:43:53] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 23:45:06,782] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/JAN_18_PIPELINE/anuvaad-corpus-tools/data-validation-pipeline/resources/data_pipeline_resources.py', reloading
[2021-01-18 23:45:06,968] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 23:45:08,362] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 23:45:08,363] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 23:45:12,103] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 23:45:12] "[31m[1mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 400 -
[2021-01-18 23:45:51,153] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/JAN_18_PIPELINE/anuvaad-corpus-tools/data-validation-pipeline/resources/data_pipeline_resources.py', reloading
[2021-01-18 23:45:51,329] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 23:45:52,659] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 23:45:52,663] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-18 23:45:54,796] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [18/Jan/2021 23:45:54] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
[2021-01-18 23:52:22,708] {_internal.py:113} MainThread INFO in _internal:  * Detected change in '/home/user2/JAN_18_PIPELINE/anuvaad-corpus-tools/data-validation-pipeline/resources/data_pipeline_resources.py', reloading
[2021-01-18 23:52:23,015] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-18 23:52:24,207] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-18 23:52:24,208] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-19 00:07:43,140] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2021-01-19 00:07:43,142] {_internal.py:113} MainThread INFO in _internal:  * Restarting with stat
[2021-01-19 00:07:43,946] {_internal.py:113} MainThread WARNING in _internal:  * Debugger is active!
[2021-01-19 00:07:43,948] {_internal.py:113} MainThread INFO in _internal:  * Debugger PIN: 317-946-547
[2021-01-19 00:07:47,822] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [19/Jan/2021 00:07:47] "[37mPOST /data_pipeline/dataset_validation HTTP/1.1[0m" 200 -
